Sprint 6/dog food
evikary/react-dog-food pull request #6
Opened 2024-05-27 08:41 UTC by evikary

2024-05-31 16:46 UTC, lelderbe requested changes
Классно сделано 👍 Ты молодец)
Оставил комментарии, где кое-что старое убрать и где кое-что можно улучшить.
Кстати, этот ПР нацелен в ветку main, но в этой ветке отсутствуют изменения из ветки 5 и мне пришлось повторно видеть все изменения которые вносились в ПР для 5й ветки :(

2024-05-31 16:46 UTC, lelderbe commented on src/app/index.tsx
> +				<Route path='/products/:idProduct' element={<SingleProductPage />} /> */}
Тут остался закомментированный код, забыла его удалить или сохранила как альтернативный вариант?

2024-05-31 16:46 UTC, lelderbe commented on src/storage/slices/buy-slice.ts
> +					item.checked = item.checked ? false : true;
здесь происходит инверсия состояния, обычно это записывается без тернарника, попробуй через логическую операцию "НЕ"

2024-05-31 16:46 UTC, lelderbe commented on src/storage/slices/buy-slice.ts
> +				item.checked = action.payload ? true : false;
здесь можно написать ещё проще, без тернарника, подумай, как

2024-05-31 16:46 UTC, lelderbe commented on src/storage/slices/buy-slice.ts
> +			state.forEach((item) => {
Можно написать чуть оптимальней с помощью find (ведь по сути ты хочешь найти нужный элемент, а лучший метод для этого - find)
forEach будет перебирать все элементы, даже если нужный элемент будет первым из всех
find вернёт найденный элемент и не станет перебирать остальные элементы после найденного

2024-05-31 16:46 UTC, lelderbe commented on src/components/buy-card-list/buy-card-list.tsx
> +	const [check, setCheck] = useState(false);
Здесь можно без useState и без useEffect. Когда ты устанавливаешь check через setCheck это приводит к ещё одному лишнему ререндеру. check можно рассчитывать как обычную переменную

2024-05-31 16:46 UTC, lelderbe commented on src/components/buy-card-list/buy-card-list.tsx
> +					p: '16px',
ого, p - это padding? Круто, не знал)

2024-05-31 16:46 UTC, lelderbe commented on src/components/buy-card-list/buy-card-list.tsx
> +						{allSum(cards) - allDiscount(cards)} ₽
allSum и allDiscount уже вычислялись выше и вновь вычисляются здесь, получается в два раза больше вычислений, чем требуется :( Хорошо бы избавиться от лишних вычислений

2024-05-31 16:46 UTC, lelderbe commented on src/components/card-product/in-basket-button/in-basket-button.tsx
> +function InBasketBtn({ id }: InBasketBtnProps) {
Интересная умная кнопка, как появится возможность, склонирую и потестирую.
Тут не получается так, что если уже набрано 10штук в корзине, я иду на страницу с товарами и кнопка добавления в корзину доступна, но когда я её кликаю, появляется надпись, что товара нет? Или надпись об отсутствии товара будет сразу? Хотелось бы видеть сразу. Я засомневался, читая код.

2024-05-31 16:46 UTC, lelderbe commented on src/components/header/header.tsx
> +	const { data } = useGetUserQuery();
Здесь data - это currentUser, нужен ли currentUser двумя строчками ниже, который достаётся из стора? :/ Какие-то два currentUser'a получаются

2024-05-31 16:46 UTC, lelderbe commented on src/components/header/header.tsx
> +								badgeContent={currentUser && data?.likes && data.likes.length}
Возможен короткий вариант: `{data?.likes?.length}`

2024-05-31 16:46 UTC, lelderbe commented on src/hooks/useSearch.ts
> +	// console.log(Object.fromEntries(searchParams.entries()));
\-

2024-05-31 16:46 UTC, lelderbe commented on src/pages/basket-page/place-on-order/place-on-order.tsx
> +function PlaceOnOrder() {
Если кнопка будет где-то ещё переиспользоваться, то выделение в отдельный компонент оправдано.  Задел на будущее?

2024-05-31 16:46 UTC, lelderbe commented on src/pages/home/home-page.tsx
> +					<Link to={path.products} style={{ textDecoration: 'none' }}>
На заметку: можно ещё атрибутом убирать подчёркивание: `underline='none'`

2024-05-31 16:46 UTC, lelderbe commented on src/pages/my-data/my-data.tsx
> +				height: 'calc(100vh - 192px - 96px)',
Захардкоженные расчёты, кажется, больше не нужны

2024-05-31 16:46 UTC, lelderbe commented on src/pages/reviews/reviews-page.tsx
> +		<Container component='main' sx={{ height: 'calc(100vh - 192px - 96px)' }}>
Тут тоже хардкод высоты остался

2024-05-31 16:46 UTC, lelderbe commented on src/pages/sign-in-page/sign-in-page.tsx
> +		<Container component='main' sx={{ height: 'calc(100vh - 192px - 96px)' }}>
И тут

2024-05-31 16:46 UTC, lelderbe commented on src/pages/sign-up-page/sign-up-page.tsx
> +		<Container component='main' sx={{ height: 'calc(100vh - 192px - 96px)' }}>
Ну в общем, проверь везде)

2024-05-31 16:46 UTC, lelderbe commented on src/storage/slices/user-slice.ts
> +export const userSlice = createSlice({
Возможно, использование этого слайса мало где осталось и от него можно полностью отказаться, так как мы храним пользователя в RTK из-за лайков

2024-05-31 16:46 UTC, lelderbe commented on src/storage/types/type-store.ts
> +export const enum RequestStatus {
Скорей всего это перечисление должно было уйти с санками

2024-05-31 16:46 UTC, lelderbe commented on src/storage/types/type-store.ts
> +}
И этот интерфейс, наверное, не актуален

2024-05-31 16:46 UTC, lelderbe commented on src/utils/constants.ts
>  export const URL = 'https://api.v2.react-learning.ru';
Урл должен был перебраться в .env
Кстати, ты интересовалась .env.example, но я его не вижу. Ты не стала его делать или не всё запушила?

2024-06-03 07:52 UTC, evikary commented on src/app/index.tsx
> +				<Route path='/products/:idProduct' element={<SingleProductPage />} /> */}
да, забыла убрать

2024-06-03 08:02 UTC, evikary commented on src/storage/slices/buy-slice.ts
> +					item.checked = item.checked ? false : true;
ок

2024-06-03 08:02 UTC, evikary commented on src/storage/slices/buy-slice.ts
> +				item.checked = action.payload ? true : false;
хорошо

2024-06-03 08:33 UTC, evikary commented on src/storage/slices/buy-slice.ts
> +			state.forEach((item) => {
+

2024-06-03 08:34 UTC, evikary commented on src/storage/slices/buy-slice.ts
> +			state.forEach((item) => {
есть)

2024-06-03 08:58 UTC, evikary commented on src/components/buy-card-list/buy-card-list.tsx
> +	const [check, setCheck] = useState(false);
исправила

2024-06-03 08:58 UTC, evikary commented on src/components/buy-card-list/buy-card-list.tsx
> +					p: '16px',
)

2024-06-03 08:59 UTC, evikary commented on src/components/buy-card-list/buy-card-list.tsx
> +						{allSum(cards) - allDiscount(cards)} ₽
перенеси свои функции в utils))

2024-06-03 09:59 UTC, evikary commented on src/components/card-product/in-basket-button/in-basket-button.tsx
> +function InBasketBtn({ id }: InBasketBtnProps) {
переделала

2024-06-03 10:00 UTC, evikary commented on src/hooks/useSearch.ts
> +	// console.log(Object.fromEntries(searchParams.entries()));
специально)

2024-06-03 11:28 UTC, evikary commented on src/components/header/header.tsx
> +	const { data } = useGetUserQuery();
исправила

2024-06-03 11:28 UTC, evikary commented on src/components/header/header.tsx
> +								badgeContent={currentUser && data?.likes && data.likes.length}
исправила

2024-06-03 11:31 UTC, evikary commented on src/pages/basket-page/place-on-order/place-on-order.tsx
> +function PlaceOnOrder() {
я считаю, что это отдельный компонент и вынесла и да, может использоваться в будущем

2024-06-03 11:33 UTC, evikary commented on src/pages/home/home-page.tsx
> +					<Link to={path.products} style={{ textDecoration: 'none' }}>
ок

2024-06-03 11:37 UTC, evikary commented on src/pages/my-data/my-data.tsx
> +				height: 'calc(100vh - 192px - 96px)',
исправила

2024-06-03 11:40 UTC, evikary commented on src/pages/reviews/reviews-page.tsx
> +		<Container component='main' sx={{ height: 'calc(100vh - 192px - 96px)' }}>
убрала

2024-06-03 11:40 UTC, evikary commented on src/pages/sign-in-page/sign-in-page.tsx
> +		<Container component='main' sx={{ height: 'calc(100vh - 192px - 96px)' }}>
убрала

2024-06-03 11:40 UTC, evikary commented on src/pages/sign-up-page/sign-up-page.tsx
> +		<Container component='main' sx={{ height: 'calc(100vh - 192px - 96px)' }}>
(((

2024-06-03 11:42 UTC, evikary commented on src/storage/slices/user-slice.ts
> +export const userSlice = createSlice({
пока оставлю

2024-06-03 11:44 UTC, evikary commented on src/storage/types/type-store.ts
> +export const enum RequestStatus {
убрала

2024-06-03 11:45 UTC, evikary commented on src/storage/types/type-store.ts
> +}
убрала

2024-06-03 11:52 UTC, merged